#!/bin/bash
# Remote, defaults to 'origin'
r=${1:-origin}

curbranch=$(git currentbranch)
echo "Pulling updates into all local branches"
echo "Working against remote: ${r}"
echo "You are in ${curbranch}"

git fetch ${r}

for b in $(git branch|sed -e 's/\*//'); do
    # skip some branches (wip_, MDL-, TODO)
    if [[ ${b} =~ wip_|MDL-|TODO|^ci$ ]]; then
        echo "skipping ${b}"
        continue
    fi
    # detect if remote branch exists
    e=$(git branch -r | grep ${r}/${b}$ | wc -l)
    if [[ $e -eq 0 ]]; then
        echo "skipping ${b}. Missing in remote: ${r}"
        continue;
    fi
    # skip branches if there aren't changes
    if [[ $(git rev-parse ${b}) = $(git rev-parse ${r}/${b}) ]];then
        echo "skipping ${b}. No changes with remote: ${r}/${b}"
        continue;
    fi
    echo "checking out ${b}..."
    git checkout ${b}
    echo "pulling updates from ${b}...(keeping local changes on top)"
    git rebase -r ${r}/${b}
done

echo "Returning to ${curbranch}"
git checkout ${curbranch}
